version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipservices/test}
    links:
      - service
    environment:
      - HTTP_HOST=service
      - HTTP_PORT=8080

  service:
    image: pipservices/service-jobs-node:latest
    environment:
      - HTTP_ENABLED=true
      - HTTP_PORT=8080
